server:
  port: 8088
---
spring:
  profiles: dev
  jpa:
    generate-ddl: true
    show-sql: true
---
spring:
  profiles: prod
---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: todo
    password: todo
    driver-class-name: com.mysql.jdbc.Driver